### ISSUE TITLE
; searches the wrong way when using F

### ISSUE THREAD

**Issue by JonnyRa** [chrisbra/improvedft#5]
Like with n and search if you do a reverse search (eg ?) then n will head in the direction of travel.

Likewise for f &F ; goes forwards and backwards respectively.

The plugin does not respect this and goes forward when repeating an F search

**Comment by chrisbra** [comment]
That is a feature. If you do not like it, :h improvedft-consistent-comma

**Comment by JonnyRa** [comment]
Ok I'll give that a go.  Might be worth amending the docs - right at the top they say "the |,| and |;|
command should just work as expected."

I have just read the bit about consistent commas.  Is it supposed to be on by default?  The docs seem to say you have to switch it on

My guess the reason that vim uses `;` to repeat is that it is on the home row and easier to find - you are basically always going to hit that if it doesn't go where you want as its unlikely you would have searched in the wrong direction.  I certainly prefer that

**Comment by JonnyRa** [comment]
Hi.

It appears the variable is unset by default and setting it has no effect either way.

I have tried both

    let g:ft_improved_consistent_comma = 1
and 
    let g:ft_improved_consistent_comma = 0

in my vimrc and resourced but with no effect - both options always result in `;` doing a forward search for the last typed character

**Comment by JonnyRa** [comment]
Also `:h improvedft-consistent-comma ` doesn't work.  I have tried various permutations and the only thing I can type to get me into the help is `:h ft_improved` - no suffixes seem to work.

Sorry I'm not trying to nitpick, just thought you'd want to know.

**Comment by chrisbra** [comment]
(sorry for answering late, i overlooked your comments).
Looks like you were right, and it didn't work as expected. Please try again, it should be fixed now.

Note: :h improved-consistent_comma should work, if this doesn't work, you most likely do not have the latest version installed.

Best,
Christian
