### ISSUE TITLE
Case-insensitive fx doesn't jump to capital X

### ISSUE THREAD

**Issue by DarthFloopy** [chrisbra/improvedft#6]
If I put `let g:ft_improved_ignorecase = 1` in my vimrc and then open Vim and type `f<some-lowercase-letter>`, and there are matching capital letters in the same line, but also matching lowercase letters in the same line, the cursor jumps to the first matching lowercase letter, instead of the desired behavior of jumping to the first matching uppercase or lowercase letter.
 - The `t` command jumps analogously, as far as I can tell.
 - The `;` and `,` operators don't seem to have this problem.

(There may also be some similar behavior with `F` and `T`, but I haven't tested that.)

I am on Vim 8.2.

**Comment by chrisbra** [comment]
Interesting, nobody noticed. I think I have fixed it now. Thanks.
